pipeline {
    agent any
    tools {
        maven "maven"  // Definir Maven instalado en Jenkins
    }
    stages {
        stage('Checkout Code') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/main']],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/neruiz3/Evaluacion_1']]
                )
            }
        }

        stage('Build Maven') {
            steps {
                dir('PrestaBank-Backend') {  // Bloque 'dir' dentro de 'steps'
                    bat 'mvn clean package'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('PrestaBank-Backend') {  // Ejecutar tests en el subdirectorio correcto
                    bat 'mvn test'
                }
            }
        }

        stage('Build and Push Image to Docker Hub') {
            steps {
                dir('PrestaBank-Backend'){
                    script {
                        withDockerRegistry(credentialsId: 'docker-credentials') {
                            bat 'docker build -t nerearuiz3/backend-image'
                            bat 'docker push nerearuiz3/backend-image'
                        }
                    }
                }
            }
        }
    }
}